[project]
name = "fullstack-mlops-aws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "zenml>=0.80.1",
]

[tool.uv.workspace]
members = ["fastapi-app-1"]
