apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zenml
  template:
    metadata:
      labels:
        app: zenml
    spec:
      containers:
        - name: zenml
          image: zenmldocker/zenml-server:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: zenml-data
              mountPath: /zenml
      volumes:
        - name: zenml-data
          emptyDir: {}
