apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          command: ["mlflow"]
          args:
            - server
            - --host
            - 0.0.0.0
            - --port
            - "5000"
            - --backend-store-uri
            - sqlite:///mlflow.db
            - --default-artifact-root
            - s3://dev-mlflow-full-stack-mlops/mlflow-artifacts
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_TRACKING_USERNAME
              value: "admin"
            - name: MLFLOW_TRACKING_PASSWORD
              value: "password"
            - name: MLFLOW_FLASK_SERVER_SECRET_KEY
              value: "password_key"
            - name: AWS_REGION
              value: "eu-west-2"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: access_key
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: secret_key
          volumeMounts:
            - name: mlflow-data
              mountPath: /mlflow
      volumes:
        - name: mlflow-data
          emptyDir: {}
